[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_ENV = "production"
  NEXTAUTH_SECRET = "study-tracker-nextauth-secret-key"
  # Will update this after backend is deployed
  NEXT_PUBLIC_STRAPI_URL = "https://study-tracker-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
